package com.ssm.bean;

import java.math.BigDecimal;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.type
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.title
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.imgURL
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.manufacturer
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    private String manufacturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.evaluate
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    private Integer evaluate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.type
     *
     * @return the value of goods.type
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.type
     *
     * @param type the value for goods.type
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.title
     *
     * @return the value of goods.title
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.title
     *
     * @param title the value for goods.title
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.imgURL
     *
     * @return the value of goods.imgURL
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.imgURL
     *
     * @param imgurl the value for goods.imgURL
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.manufacturer
     *
     * @return the value of goods.manufacturer
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.manufacturer
     *
     * @param manufacturer the value for goods.manufacturer
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.evaluate
     *
     * @return the value of goods.evaluate
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    public Integer getEvaluate() {
        return evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.evaluate
     *
     * @param evaluate the value for goods.evaluate
     *
     * @mbg.generated Sun Jan 05 17:51:18 HKT 2020
     */
    public void setEvaluate(Integer evaluate) {
        this.evaluate = evaluate;
    }
}