package com.ssm.mapper;

import com.ssm.bean.Goods;
import java.util.List;

public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Jan 05 17:47:28 HKT 2020
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Sun Jan 05 17:47:28 HKT 2020
     */
    List<Goods> selectAll();
}