package com.ssm.mapper;

import com.ssm.bean.Users;
import java.util.List;

public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Jan 05 17:47:28 HKT 2020
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun Jan 05 17:47:28 HKT 2020
     */
    List<Users> selectAll();
}